name: Create weekly meeting discussion with comments

on:
  workflow_dispatch:
  schedule:
    # NOTE: Discussionを作成するタイミングに合わせて修正してください。
    # 例:
    # 毎週水曜13:00に作成する → cron: "0 4 * * wed"
    # 毎週月曜8:00に作成する → cron: "0 23 * * sun"
    # ref: https://docs.github.com/ja/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
    - cron: "0 4 * * wed"

jobs:
  calc_next_weekly_date:
    uses: route06/actions/.github/workflows/calc_next_date.yml@v2
    with:
      interval: weekly
      # NOTE: ミーティング実施曜日を指定してください。
      # 金曜日に実施する場合は target_day: friday となります。
      target_day: wednesday
  
  # GitHub Discussion を作成する
  create_discussion:
    needs: [calc_next_weekly_date]
    uses: route06/actions/.github/workflows/create_gh_discussion.yml@v2
    with:
      # NOTE: タイトルを修正してください。以下は、「yyyy/mm/dd タイトル」となります。
      # 「yyyy/mm/dd 週次定例」としたい場合は title: ${{ needs.calc_next_weekly_date.outputs.next_date }} 週次定例 となります。
      title: ${{ needs.calc_next_weekly_date.outputs.next_date }} タイトル
      # NOTE: 設定したいカテゴリに合わせて修正してください。
      # 指定するのは、各カテゴリを選択した時のURL末尾の文字列です。
      # https://github.com/<org>/<repo>/discussions/categories/meeting-notes
      # カテゴリ Meeting notesの場合は、上記のURLのように "meeting-notes" となるため category_slug: meeting-notes となります。
      category_slug: ideas
      # NOTE: 本文に利用するテンプレートファイルを作成し、パスを指定してください。
      # 以下は、リポジトリに "_templates/weekly_meeting_discussion/body.md" というファイルがある想定です。
      # ファイルが見つからない場合、本文が空のDiscussionが作成されます。
      description_template_path: _templates/weekly_meeting_discussion/body.md

  # [任意] 作成した Discussion にコメント1を追加する
  # NOTE: 不要なら削除して下さい。
  add_comment1:
    needs: create_discussion
    uses: route06/actions/.github/workflows/add_discussion_comment.yml@v2
    permissions:
      contents: read
      discussions: write
    with:
      discussion_id: ${{ needs.create_discussion.outputs.discussion_id }}
      # NOTE: 1番目のコメントに利用するテンプレートファイルを作成し、パスを指定してください。
      # 以下は、リポジトリに "_templates/weekly_meeting_discussion/comment1.md" というファイルがある想定です。
      # ファイルが見つからない場合、本文が空のコメントが追加されます。
      comment_template_path: _templates/weekly_meeting_discussion/comment1.md

  # [任意] 追加したコメント1に返信する
  # NOTE: 不要なら削除して下さい。
  reply_to_comment1:
    needs: add_comment1
    uses: route06/actions/.github/workflows/add_discussion_comment.yml@v2
    permissions:
      contents: read
      discussions: write
    with:
      discussion_id: ${{ needs.add_comment1.outputs.discussion_id }}
      # NOTE: コメント1への返信に利用するテンプレートファイルを作成し、パスを指定してください。
      # 以下は、リポジトリに "_templates/weekly_meeting_discussion/comment1_reply1.md" というファイルがある想定です。
      # ファイルが見つからない場合、本文が空の返信が追加されます。
      comment_template_path: _templates/weekly_meeting_discussion/comment1_reply1.md
      reply_to_comment_id: ${{ needs.add_comment1.outputs.comment_id }}

  # [任意] 作成した Discussion にコメント2を追加する
  # NOTE: 不要なら削除して下さい。
  add_comment2:
    needs: add_comment1
    uses: route06/actions/.github/workflows/add_discussion_comment.yml@v2
    permissions:
      contents: read
      discussions: write
    with:
      discussion_id: ${{ needs.add_comment1.outputs.discussion_id }}
      # NOTE: 2番目のコメントに利用するテンプレートファイルを作成し、パスを指定してください。
      # 以下は、リポジトリに "_templates/weekly_meeting_discussion/comment2.md" というファイルがある想定です。
      # ファイルが見つからない場合、本文が空のコメントが追加されます。
      comment_template_path: _templates/weekly_meeting_discussion/comment2.md
