on:
  discussion_comment:
    types: [created]

jobs:
  discussion_commented:
    if: github.event.discussion && github.event.comment
    uses: route06/actions/.github/workflows/_discussions-comment-notice.yml@v1
    secrets:
      slack-webhook-url: ${{ secrets.SLACK_GHD_WEBHOOK_URL }}
