on:
  discussion_comment:
    types: [created]

jobs:
  discussion_commented:
    if: github.event.discussion && github.event.comment
    uses: route06/actions/.github/workflows/gh_discussion_comment_to_slack.yml@v2
    secrets:
      slack-webhook-url: ${{ secrets.SLACK_GHD_WEBHOOK_URL }}
